/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as TtybRouteImport } from './routes/ttyb'
import { Route as TenantsIndexRouteImport } from './routes/tenants.index'
import { Route as TenantsTenantIdRouteImport } from './routes/tenants.$tenantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const TtybRoute = TtybRouteImport.update({
  id: '/ttyb',
  path: '/ttyb',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsIndexRoute = TenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantsRoute,
} as any)
const TenantsTenantIdRoute = TenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => TenantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/ttyb': typeof TtybRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ttyb': typeof TtybRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants': typeof TenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tenants': typeof TenantsRouteWithChildren
  '/ttyb': typeof TtybRoute
  '/tenants/$tenantId': typeof TenantsTenantIdRoute
  '/tenants/': typeof TenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tenants' | '/ttyb' | '/tenants/$tenantId' | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ttyb' | '/tenants/$tenantId' | '/tenants'
  id:
    '__root__' | '/' | '/tenants' | '/ttyb' | '/tenants/$tenantId' | '/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantsRoute: typeof TenantsRouteWithChildren
  TtybRoute: typeof TtybRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ttyb': {
      id: '/ttyb'
      path: '/ttyb'
      fullPath: '/ttyb'
      preLoaderRoute: typeof TtybRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants/': {
      id: '/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof TenantsIndexRouteImport
      parentRoute: typeof TenantsRoute
    }
    '/tenants/$tenantId': {
      id: '/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof TenantsTenantIdRouteImport
      parentRoute: typeof TenantsRoute
    }
  }
}

interface TenantsRouteChildren {
  TenantsTenantIdRoute: typeof TenantsTenantIdRoute
  TenantsIndexRoute: typeof TenantsIndexRoute
}

const TenantsRouteChildren: TenantsRouteChildren = {
  TenantsTenantIdRoute: TenantsTenantIdRoute,
  TenantsIndexRoute: TenantsIndexRoute,
}

const TenantsRouteWithChildren =
  TenantsRoute._addFileChildren(TenantsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantsRoute: TenantsRouteWithChildren,
  TtybRoute: TtybRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
